//
//  AdditionalLayerInformationKey.swift
//  
//
//  Created by Hugh Bellamy on 20/01/2021.
//

public enum AdditionalLayerInformationKey: String {
    case effectsLayer = "lrFX"
    case typeToolInfo = "tySh"
    case unicodeLayerName = "luni"
    case layerID = "lyid"
    case objectBasedEffectsLayerInfo = "lfx2"
    case blendClippingElements = "clbl"
    case blendInteriorElements = "infx"
    case knockout = "knko"
    case protected = "lspf"
    case sheetColor = "lclr"
    case referencePoint = "fxrp"
    case gradientMap = "grdm"
    case sectionDivider = "lsct"
    case channelBlendingRestrictions = "brst"
    case solidColorSheet = "SoCo"
    case patternFill = "PtFl"
    case gradientFill = "GdFl"
    case vectorMaskSettingVmsk = "vmsk"
    case vectorMaskSettingVsms = "vsms"
    case typeToolObject = "TySh"
    case foreignEffectID = "ffxi"
    case layerNameSource = "lnsr"
    case patternData = "shpa"
    case metadata = "shmd"
    case layerVersion = "lyvr"
    case transparencyShapesLayer = "tsly"
    case layerMaskAsGlobalMask = "lmgm"
    case vectorMaskAsGlobalMask = "vmgm"
    case brightnessAndContrast = "brit"
    case channelMixer = "mixr"
    case colorLookup = "clrL"
    case placedLayer = "PlLd"
    case linkedLayerlnkD = "lnkD"
    case linkedLayerlnk2 = "lnk2"
    case linkedLayerlnk3 = "lnk3"
    case photoFilter = "phfl"
    case blackAndWhite = "blwh"
    case contentGeneratorExtraData = "CgEd"
    case textEngineData = "Txt2"
    case vibrance = "vibA"
    case unicodePathNames = "pths"
    case animationEffects = "anFX"
    case filterMask = "FMsk"
    case placedLayerData = "SoLd"
    case vectorStrokeData = "vstk"
    case vectorStrokeContent = "vscg"
    case usingAlignedRendering = "sn2P"
    case vectorOriginationData = "vogk"
    case pixelSourceDataPxDC = "PxSc"
    case compositorUsed = "cinf"
    case pixelSourceDataPxSD = "PxSD"
    case artboardDataArtb = "artb"
    case artboardDataArtd = "artd"
    case artboardDataAbdd = "abdd"
    case smartObjectLayerData = "SoLE"
    case savingMergedTransparencyMtrn = "Mtrn"
    case savingMergedTransparencyMt16 = "Mt16"
    case savingMergedTransparencyMt32 = "Mt32"
    case userMask = "LMsk"
    case exposure = "expA"
    case filterEffectsFXid = "FXid"
    case filterEffectsFEid = "FEid"
    case opacity = "iOpa"
    case hueSaturation2 = "hue2"
    case colorBalance = "blnc"
    case levels = "levl"
    case curves = "curv"
    case invert = "nvrt"
    case posterize = "post"
    case threshold = "thrs"
    case selectiveColor = "selc"
    case lfxs = "lfxs"
}
